// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gls_blocks_cpp
Rcpp::List gls_blocks_cpp(const arma::mat& X_tilde, const arma::cube& A_arr, const arma::cube& AM_arr, const arma::mat& Ar, const arma::mat& G_inv, double rank_tol);
RcppExport SEXP _CondPED_gls_blocks_cpp(SEXP X_tildeSEXP, SEXP A_arrSEXP, SEXP AM_arrSEXP, SEXP ArSEXP, SEXP G_invSEXP, SEXP rank_tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X_tilde(X_tildeSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type A_arr(A_arrSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type AM_arr(AM_arrSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Ar(ArSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type G_inv(G_invSEXP);
    Rcpp::traits::input_parameter< double >::type rank_tol(rank_tolSEXP);
    rcpp_result_gen = Rcpp::wrap(gls_blocks_cpp(X_tilde, A_arr, AM_arr, Ar, G_inv, rank_tol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CondPED_gls_blocks_cpp", (DL_FUNC) &_CondPED_gls_blocks_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_CondPED(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
