# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gls_blocks_cpp <- function(X_tilde, A_arr, AM_arr, Ar, G_inv, rank_tol) {
    .Call(`_CondPED_gls_blocks_cpp`, X_tilde, A_arr, AM_arr, Ar, G_inv, rank_tol)
}

